### ISSUE TITLE
I'm getting counters as unsupported attribute

### ISSUE THREAD

**Issue by dougg0k** [cressie176/rascal-redis-counter#11]
rascal@14.3.0
rascal-redis-counter@0.2.4
rabbitmq#3.9.10
```
err: {
      "type": "Error",
      "message": "Vhost: redeliveries refers to an unsupported attribute: counters",
      "stack":
          Error: Vhost: redeliveries refers to an unsupported attribute: counters
              at validateAttributes (/app/node_modules/rascal/lib/config/validate.js:34:31)
              at validateVhost (/app/node_modules/rascal/lib/config/validate.js:22:5)
              at /app/node_modules/lodash/lodash.js:4967:15
              at baseForOwn (/app/node_modules/lodash/lodash.js:3032:24)
              at /app/node_modules/lodash/lodash.js:4936:18
              at Function.forEach (/app/node_modules/lodash/lodash.js:9410:14)
              at validateVhosts (/app/node_modules/rascal/lib/config/validate.js:18:7)
              at /app/node_modules/rascal/lib/config/validate.js:7:5
              at apply (/app/node_modules/lodash/lodash.js:489:27)
              at wrapper (/app/node_modules/lodash/lodash.js:5101:16)
              at /app/node_modules/async/dist/async.js:1984:20
              at /app/node_modules/async/dist/async.js:1925:13
              at replenish (/app/node_modules/async/dist/async.js:443:21)
              at /app/node_modules/async/dist/async.js:448:13
              at eachOfLimit$1 (/app/node_modules/async/dist/async.js:474:34)
              at awaitable (/app/node_modules/async/dist/async.js:211:32)
    }
```
```
import redisCounter from "rascal-redis-counter";

const brokerCreated = await Broker.create(brokerConfig, {
		counters: { redisCounter },
});
```

```
redeliveries: {
	counters: {
		shared: {
			type: "redisCounter",
			client: {
				host: config.redisUrl,
				db: 7,
			},
		},
	},
},
```

**Comment by cressie176** [comment]
Hi @dougg0k,

My first guess is that the redeliveries config might be nested inside vhost block, hence the message "Vhost: **redeliveries** refers to an unsupported attribute: counters". Rascal is treating "redeliveries" as if it were a vhost.

**Comment by dougg0k** [comment]
@cressie176 You are correct, thanks for the help.
